name: Playwright Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright Browsers
      run: |
        playwright install --with-deps ${{ matrix.browser }}
    
    - name: Run Playwright tests
      run: |
        BROWSER=${{ matrix.browser }} pytest --browser ${{ matrix.browser }}
      env:
        BROWSER: ${{ matrix.browser }}
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.browser }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-screenshots-${{ matrix.browser }}
        path: test-results/screenshots/
        retention-days: 30 