name: Playwright Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    name: Playwright Tests (Chromium)
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright Browsers (Linux)
      if: runner.os == 'Linux'
      run: playwright install --with-deps chromium

    - name: Install Playwright Browsers (Windows/macOS)
      if: runner.os != 'Linux'
      run: playwright install chromium
    
    - name: Run Playwright tests
      run: |
        BROWSER=chromium pytest --browser chromium
      env:
        BROWSER: chromium
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-chromium
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-screenshots-chromium
        path: test-results/screenshots/
        retention-days: 30 